version: '3.3'
services:
  db:
    image: mariadb:10.7
    restart: always
    env_file:
      - ./env/db.env
    volumes:
      - ./db:/var/lib/mysql
  phpmyadmin:
      image: phpmyadmin:latest
      restart: always
      ports:
        - 8080:80
      env_file:
        - ./env/db.env
      depends_on:
        - db
  web:
    image: fabiofrances/glpi:latest
    restart: always
    ports:
      - 80:80
    depends_on:
      - db